import { manrope } from './fonts';
import Header from './components/header/Header'
import "./globals.scss";

export const metadata = {
  title: "Audiophile e-commerce website",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
